name: Redeploy Pans

on:
  push:
    branches:
      - master
      - develop

jobs:
  redeploy:
    runs-on: [self-hosted, home-server]

    steps:
      - name: Deploy Prod
        if: github.ref == 'refs/heads/master'
        run: |
          cd "$PANS_PROD_PATH"
          docker compose restart
        env:
          PANS_PROD_PATH: ${{ vars.PANS_PROD_PATH }}

      - name: Deploy Dev
        if: github.ref == 'refs/heads/develop'
        run: |
          cd "$PANS_DEV_PATH"
          docker compose restart
        env:
          PANS_DEV_PATH: ${{ vars.PANS_DEV_PATH }}

      - name: Deploy LAN
        if: github.ref == 'refs/heads/develop'
        run: |
          cd "$PANS_LAN_PATH"
          docker compose restart
        env:
          PANS_DEV_PATH: ${{ vars.PANS_LAN_PATH }}
